In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
folder = r"C:\Users\admin\Downloads\Data Set For Task-20260821T102726Z-1-001\Data Set For Task\Churn Prdiction Data"
print(os.listdir(folder))

['churn-bigml-20.csv', 'churn-bigml-80.csv']

In [3]:
df = pd.read_csv(r"C:\Users\admin\Downloads\Data Set For Task-20260821T102726Z-1-001\Data Set For Task\Churn Prdiction Data\churn-bigml-80.csv")

In [4]:
df.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

In [5]:
print("Shape:", df.shape)

Shape: (2666, 20)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   2666 non-null   str
 1   Account length          2666 non-null   int64
 2   Area code               2666 non-null   int64
 3   International plan      2666 non-null   str
 4   Voice mail plan         2666 non-null   str
 5   Number vmail messages   2666 non-null   int64
 6   Total day minutes       2666 non-null   float64
 7   Total day calls         2666 non-null   int64
 8   Total day charge        2666 non-null   float64
 9   Total eve minutes       2666 non-null   float64
 10  Total eve calls         2666 non-null   int64
 11  Total eve charge        2666 non-null   float64
 12  Total night minutes     2666 non-null   float64
 13  Total night calls       2666 non-null   int64
 14  Total night charge      2666 non-null   float64
 15  Total intl minutes      2666 non-null   float64
 16  Total intl calls        2666 non-null   int64
 17  Total intl charge       2666 non-null   float64
 18  Customer service calls  2666 non-null   int64
 19  Churn                   2666 non-null   bool
dtypes: bool(1), float64(8), int64(8), str(3)
memory usage: 415.1 KB

In [7]:
df.columns.tolist()

['State',
 'Account length',
 'Area code',
 'International plan',
 'Voice mail plan',
 'Number vmail messages',
 'Total day minutes',
 'Total day calls',
 'Total day charge',
 'Total eve minutes',
 'Total eve calls',
 'Total eve charge',
 'Total night minutes',
 'Total night calls',
 'Total night charge',
 'Total intl minutes',
 'Total intl calls',
 'Total intl charge',
 'Customer service calls',
 'Churn']

In [8]:
df["Churn"].value_counts()

Churn
False    2278
True      388
Name: count, dtype: int64

In [9]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [10]:
print("Duplicated Rows:", df.duplicated().sum())

Duplicated Rows: 0

In [11]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [12]:
print("Features:",X.shape)
print("Target:", y.shape)

Features: (2666, 19)
Target: (2666,)

In [13]:
categorical_cols = X.select_dtypes(include=["object"]).columns
print("Categorical Columns:")
print(categorical_cols.tolist())

Categorical Columns:
['State', 'International plan', 'Voice mail plan']

C:\Users\admin\AppData\Local\Temp\ipykernel_6336\3922715622.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object"]).columns

In [14]:
numerical_cols = X.select_dtypes(include=["int64","float64"]).columns
print("Munerical columns:")
print(numerical_cols.tolist())

Munerical columns:
['Account length', 'Area code', 'Number vmail messages', 'Total day minutes', 'Total day calls', 'Total day charge', 'Total eve minutes', 'Total eve calls', 'Total eve charge', 'Total night minutes', 'Total night calls', 'Total night charge', 'Total intl minutes', 'Total intl calls', 'Total intl charge', 'Customer service calls']

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [16]:
preprocessor = ColumnTransformer(transformers=[("num",StandardScaler(),numerical_cols),
("cat",OneHotEncoder(handle_unknown="ignore"),categorical_cols)])

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [20]:
logistic_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [21]:
print(logistic_model.steps)

[('preprocessor', ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['Account length', 'Area code', 'Number vmail messages',
       'Total day minutes', 'Total day calls', 'Total day charge',
       'Total eve minutes', 'Total eve calls', 'Total eve charge',
       'Total night minutes', 'Total night calls', 'Total night charge',
       'Total intl minutes', 'Total intl calls', 'Total intl charge',
       'Customer service calls'],
      dtype='str')),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 Index(['State', 'International plan', 'Voice mail plan'], dtype='str'))])), ('classifier', LogisticRegression(max_iter=1000))]

In [22]:
logistic_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Account length', 'Area code', 'Number vmail messages',
       'Total day minutes', 'Total day calls', 'Total day charge',
       'Total eve minutes', 'Total eve calls', 'Total eve charge',
       'Total night minutes', 'Total night calls', 'Total night charge',
       'Total intl minutes', 'Total intl calls', 'Total intl charge',
       'Customer service calls'],
      dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['State', 'International plan', 'Voice mail plan'], dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [23]:
y_pred_lr = logistic_model.predict(X_test)

In [24]:
from sklearn.metrics import(accuracy_score,precision_score,recall_score,f1_score,classification_report)

In [25]:
print("Logistic Regression")
print("      ")
print("Accuracy:",accuracy_score(y_test,y_pred_lr))
print("Precision:",precision_score(y_test,y_pred_lr))
print("Recall:",recall_score(y_test,y_pred_lr))
print("F1 Score:",f1_score(y_test,y_pred_lr))

Logistic Regression

Accuracy: 0.8426966292134831
Precision: 0.425
Recall: 0.21794871794871795
F1 Score: 0.288135593220339

In [26]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

       False       0.88      0.95      0.91       456
        True       0.42      0.22      0.29        78

    accuracy                           0.84       534
   macro avg       0.65      0.58      0.60       534
weighted avg       0.81      0.84      0.82       534

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

In [28]:
decision_tree_model = Pipeline(steps=[("preprocessor",preprocessor),("classifier",DecisionTreeClassifier(random_state=42))])

In [29]:
decision_tree_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Account length', 'Area code', 'Number vmail messages',
       'Total day minutes', 'Total day calls', 'Total day charge',
       'Total eve minutes', 'Total eve calls', 'Total eve charge',
       'Total night minutes', 'Total night calls', 'Total night charge',
       'Total intl minutes', 'Total intl calls', 'Total intl charge',
       'Customer service calls'],
      dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['State', 'International plan', 'Voice mail plan'], dtype='str'))])),
                ('classifier', DecisionTreeClassifier(random_state=42))])

In [30]:
y_pred_dt = decision_tree_model.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("Decision tree Results")
print("Accuracy :", accuracy_score(y_test,y_pred_dt))
print("Precision :", precision_score(y_test,y_pred_dt))
print("Recall :", recall_score(y_test,y_pred_dt))
print("F1 Score :", f1_score(y_test,y_pred_dt))

Decision tree Results
Accuracy : 0.9063670411985019
Precision : 0.6794871794871795
Recall : 0.6794871794871795
F1 Score : 0.6794871794871795

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
random_forest_model = Pipeline(steps=[("preprocessor",preprocessor),("classifier",RandomForestClassifier(n_estimators=100,random_state=42))])

In [38]:
random_forest_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Account length', 'Area code', 'Number vmail messages',
       'Total day minutes', 'Total day calls', 'Total day charge',
       'Total eve minutes', 'Total eve calls', 'Total eve charge',
       'Total night minutes', 'Total night calls', 'Total night charge',
       'Total intl minutes', 'Total intl calls', 'Total intl charge',
       'Customer service calls'],
      dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['State', 'International plan', 'Voice mail plan'], dtype='str'))])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [39]:
y_pred_rf = random_forest_model.predict(X_test)

In [41]:
print("Random Forest Classifier")
print("Accuracy :", accuracy_score(y_test,y_pred_rf))
print("Precision :", precision_score(y_test,y_pred_rf))
print("Recall :", recall_score(y_test,y_pred_rf))
print("F1 Score :", f1_score(y_test,y_pred_rf))

Random Forest Classifier
Accuracy : 0.9325842696629213
Precision : 0.9772727272727273
Recall : 0.5512820512820513
F1 Score : 0.7049180327868853

In [46]:
results = pd.DataFrame({"Model":["Logistic Regression","Decision Tree","Random Forest"],
                      "Accuracy": [accuracy_score(y_test,y_pred_lr),
                                  accuracy_score(y_test,y_pred_dt),
                                  accuracy_score(y_test,y_pred_rf)],
                      "Precision": [precision_score(y_test,y_pred_lr),
                                   precision_score(y_test,y_pred_dt),
                                   precision_score(y_test,y_pred_rf)],
                      "Recall": [recall_score(y_test,y_pred_lr),
                                recall_score(y_test,y_pred_dt),
                                recall_score(y_test,y_pred_rf)],
                      "F1 Score": [f1_score(y_test,y_pred_lr),
                                  f1_score(y_test,y_pred_dt),
                                  f1_score(y_test,y_pred_rf)
                                  ]})
results

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.842697   0.425000  0.217949  0.288136
1        Decision Tree  0.906367   0.679487  0.679487  0.679487
2        Random Forest  0.932584   0.977273  0.551282  0.704918

In [47]:
from sklearn.model_selection import GridSearchCV

In [48]:
param_grid = {"classifier_n_estimators": [100,200],
             "classifier_max_depth": [None,10,20],
              "classifier_min_samples_split": [2,5],
              "classifier_min_samples_leaf": [1,2]}

In [56]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "classifier__n_estimators": [100, 200],
    "classifier__max_depth": [10, 20]
}

grid_search = GridSearchCV(
    estimator=random_forest_model,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=1,
    error_score="raise"
)

In [57]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         Index(['Account length', 'Area code', 'Number vmail messages',
       'Total day minutes', 'Total day calls', 'Total day charge',
       'Total eve minutes', 'Total eve calls', 'Total eve charge',
       'Total night minutes', 'Total night calls', 'Total night charge',
       'Total intl minutes', 'Total intl calls', 'Total intl charge',
       'Customer service calls'],
      dtype='str')),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['State', 'International plan', 'Voice mail plan'], dtype='str'))])),
                                       ('classifier',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=1,
             param_grid={'classifier__max_depth': [10, 20],
                         'classifier__n_estimators': [100, 200]},
             scoring='f1')

In [58]:
print("Best Parameters:")
print(grid_search.best_params_)
print("\nBest Cross-Validation F1 Score:")
print(grid_search.best_score_)

Best Parameters:
{'classifier__max_depth': 20, 'classifier__n_estimators': 200}

Best Cross-Validation F1 Score:
0.7232430713689663

In [59]:
best_model = grid_search.best_estimator_
y_pred_tuned = best_model.predict(X_test)
print("Tuned Random Forest Results")
print("Accuracy :", accuracy_score(y_test,y_pred_tuned))
print("Precision :", precision_score(y_test,y_pred_tuned))
print("Recall :", recall_score(y_test,y_pred_tuned))
print("F1 Score :", f1_score(y_test,y_pred_tuned))

Tuned Random Forest Results
Accuracy : 0.9344569288389513
Precision : 1.0
Recall : 0.5512820512820513
F1 Score : 0.7107438016528925